name: Upload Python Package

on:
  release:
    types: [published]

env:
  UV_SYSTEM_PYTHON: true

jobs:
  deploy:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/pynxtools-raman
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # submodules: recursive
      - name: Install uv and use python version 3.12
        uses: astral-sh/setup-uv@v5
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          uv pip install build
      - name: Build package
        run: python -m build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1